#!/usr/bin/env python


import time

newEpochTime = int(time.time())

items = {}
with open("etc/openwrt_release") as f:
  for line in f:
    (key, val) = line.split('=')
    items[key] = val

items['DISTRIB_RELEASE_DATE'] = '\"' + str(newEpochTime) + '\"\n'

with open("etc/openwrt_release",'w') as f:
  for key in items:
    f.write(key + '=' + items[key])

with open("etc/last_update_check", "w") as f:
  f.write(str(newEpochTime * 1000) + "  N")
