#!/usr/bin/env python


import datetime

newEpochTime = int(datetime.datetime.now().strftime('%s')) - int(datetime.datetime(1970,1,1).strftime('%s'))

items = {}
with open("etc/openwrt_release") as f:
  for line in f:
    (key, val) = line.split('=')
    items[key] = val

items['DISTRIB_RELEASE_DATE'] = '\"' + str(newEpochTime) + '\"\n'

with open("etc/openwrt_release",'w') as f:
  for key in items:
    f.write(key + '=' + items[key])
f.close()
