#!/bin/bash -e
cd $(dirname $0)

echo "remove etc and www directories in build ..."
rm -rf cerowrt/files/etc
rm -rf cerowrt/files/www

echo "change DISTRIB_RELEASE_DATE in openwrt_release ..."
./changeReleaseDate

echo "push etc to build"
cp -rp etc cerowrt/files/

echo "set permissions for /etc/auth"
chmod 0700 cerowrt/files/etc/auth

echo "make www directory in build..."
mkdir cerowrt/files/www

echo "pushing frontend to build..."
cp -rp app/* cerowrt/files/www/

echo "make cgi-bin directory in build..."
mkdir cerowrt/files/www/cgi-bin

echo "pushing routerapi to build..."
cp -rp routerapi cerowrt/files/www/cgi-bin/
