#!/bin/bash -e

echo "pushing frontend to router..."
scp -P 2200 -rp app root@localhost:/www
echo "pushing backend to router..."
scp -P 2200 -rp routerapi root@localhost:/www/cgi-bin
echo "pushing wireless config.."
scp -P 2200 wireless root@localhost:/etc/config
