#!/bin/bash
cd $(dirname $0)

TARGET=root@gw.home.lan
sync() {
  ./make-templates.sh
  rsync -au app/ $TARGET:/www/
  rsync -au routerapi/ $TARGET:/www/cgi-bin/routerapi/
  date +"%Y-%m-%d %H:%M:%S synced"
}

if [ "$1" == "--continuous" ]; then
  grep -q ControlMaster ~/.ssh/config || echo "Install recommended ssh-config."
  ssh -Nf $TARGET
  sync
  inotifywait -rm -e close_write --format '%w%f' app routerapi |\
  while read line; do sync ; done
else
  sync
fi
