#!/bin/bash -e
cd $(dirname $0)

./make-templates.sh
echo "pushing frontend to router..."
rsync -avu app/ root@172.30.42.1:/www/

echo "pushing backend to router..."
rsync -avu routerapi/ root@172.30.42.1:/www/cgi-bin/routerapi/
