#!/bin/sh

### BEGIN INIT INFO
# Provides: Xvfb
# Required-Start: $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:
# Default-Start: 2 3 4 5
# Default-Stop:
### END INIT INFO

set -e
set -o nounset

NAME=Xvfb
INIT=/etc/init.d/$NAME
PROGRAM=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DISPLAY=:0

case "$1" in
  start)
start-stop-daemon --oknodo --background --make-pidfile --start --exec $PROGRAM --pidfile $PIDFILE -- $DISPLAY -screen 0 1024x768x24
;;
  stop)
start-stop-daemon --oknodo --stop --pidfile $PIDFILE
rm $PIDFILE
;;
  *)
echo "Usage: $INIT {start|stop}" >&2
exit 1
;;
esac

exit 0
