#!/usr/bin/env python2.7
import datetime
import json
import common
from get_bytecounts import get_device_and_byte_counts

[dev, privateWifiToLan, x] = get_device_and_byte_counts("privatewifitolan")
[dev, lanToPrivateWifi, x] = get_device_and_byte_counts("lantoprivatewifi")

[openWirelessDevices, openWirelessUploadUsage, openWirelessDownloadUsage] = get_device_and_byte_counts("open-wifi")
[internetUploadUsage, internetDownloadUsage] = [openWirelessUploadUsage, openWirelessDownloadUsage] 

[lanNetworkDevices, lanNetworkUploadUsage, lanNetworkDownloadUsage] = get_device_and_byte_counts("wired-lan")
lanNetworkUploadUsage -= lanToPrivateWifi
lanNetworkDownloadUsage -= privateWifiToLan
internetUploadUsage += lanNetworkUploadUsage
internetDownloadUsage += lanNetworkDownloadUsage

[privateWifiDevices, privateWifiUploadUsage, privateWifiDownloadUsage] = get_device_and_byte_counts("private-wifi")
privateWifiUploadUsage -= privateWifiToLan
privateWifiDownloadUsage -= lanToPrivateWifi
internetUploadUsage += privateWifiUploadUsage
internetDownloadUsage += privateWifiDownloadUsage


result = {
  "internet": {
    "uploadUsage"   : internetUploadUsage,
    "downloadUsage" : internetDownloadUsage
  },
  "lanNetwork": {
    "uploadUsage"   : lanNetworkUploadUsage,
    "downloadUsage" : lanNetworkDownloadUsage,
    "devices"       : lanNetworkDevices
  },
  "privateWifi": {
    "uploadUsage"   : privateWifiUploadUsage,
    "downloadUsage" : privateWifiDownloadUsage,
    "devices"       : privateWifiDevices
  },
  "openWireless": {
    "uploadUsage"   : openWirelessUploadUsage,
    "downloadUsage" : openWirelessDownloadUsage
  },
  "dateTime" : datetime.datetime.now().isoformat()
}

common.render_success(result)
