#!/usr/bin/python
import json, sys, common, os, auth

def jsonrpc_change_password():
  """Accept a JSONRPC-style change password, with parameters like so:

  {"jsonrpc":"2.0","method":"use.setpassword","params":["username","password", "oldpassword"],"id":1}
  """
  data = json.loads(sys.stdin.read())
  try:
    params = data["params"]
    username = params[0]
    new_password = params[1]
    old_password = params[2]
  except KeyError, e:
    render_error(e.__str__())
  except IndexError, e:
    render_error(e.__str__())

  a = auth.Auth("/etc/auth")
  if a.is_password(old_password):
    a.save_password(new_password)
    print "Content-Type: application/json"
    print "Set-Cookie: %s=%s; path=/; HttpOnly;" % (
      auth.Auth.AUTH_COOKIE_NAME, a.regenerate_authentication_token())
    print
    print "{}"
  else:
   common.render_error("Old password is incorrect.")

jsonrpc_change_password()
