#!/usr/bin/env python2.7
import json
import os
import sys

import auth
import common

def jsonrpc_change_password():
    """Accept a JSONRPC-style change password, with parameters like so:

    {"jsonrpc":"2.0","method":"use.setpassword","params":["username","password", "oldpassword"],"id":1}

    On successful login, set two cookies: The auth cookie, used for primary
    authentication, is HttpOnly so JS cannot access it in case of an XSS. The
    CSRF token, used to validate that POSTs come from the same origin, is
    accessible to JS so it can be included in <form>'s.
    """
    data = json.loads(sys.stdin.read())
    try:
        params = data["params"]
        username = params[0]
        new_password = params[1]
        old_password = params[2]
    except KeyError, e:
        common.render_error(e.__str__())
    except IndexError, e:
        common.render_error(e.__str__())

    a = auth.Auth()
    if a.is_password(old_password):
        if not a.save_password(new_password):
            common.render_error("Invalid password supplied.")
        remote_address = os.environ.get('REMOTE_ADDR')
        tokens = a.authenticate(new_password, remote_address)
        print "Content-Type: application/json"
        print a.login_headers(tokens)
        print
        print "{}"
    else:
     common.render_error("Old password is incorrect.")

jsonrpc_change_password()
