#!/usr/bin/env python2.7
import cgi
import json
import subprocess

import auth
import common

if subprocess.call(["python", "/lib/update/update.py", "check"]) == 0:
  ret = "not-up-to-date"
else:
  ret = "up-to-date"

result = {
  "result": {
    "status": ret
  }
}

common.render_success(result)
