#!/usr/bin/python

# Import modules for CGI handling
import cgi, json, common
from subprocess import check_output, call
from ip_address_retriever import get_internal_ip_address, get_external_ip_address

ping_output = check_output(["/bin/ping", "-c1", "google.com"])

if "error" in ping_output:
  connected = False
  ping_speed = "N/A"
else:
  connected = True
  ping_speed = ping_output.split(' ')[11].split('=')[1]


wan_ip = get_external_ip_address() 
lan_ip = get_internal_ip_address("ge00") 

result = {
	"id": 1,
	"jsonrpc": "2.0",
	"result": {
		"internet": {
			"name": "Internet",
			"uploadSpeed": "Loading",
			"uploadSpeedMetric": "mb/s",
			"downloadSpeed": "Loading",
			"downloadSpeedMetric": "mb/s",
			"pingSpeed": ping_speed,
			"pingSpeedMetric": "ms",
			"connected": connected
		},
		"lanNetwork": {
			"name": "LAN Network",
			"uploadSpeed": "Loading",
			"uploadSpeedMetric": "mb/s",
			"downloadSpeed": "Loading",
			"downloadSpeedMetric": "mb/s",
			"devices": "0"
		},
		"privateWifi": {
			"name": "Private Wifi",
			"uploadSpeed": "Loading",
			"uploadSpeedMetric": "mb/s",
			"downloadSpeed": "Loading",
			"downloadSpeedMetric": "mb/s",
			"devices": "0",
			"on": False
		},
		"openWireless": {
			"name": "Openwireless.org",
			"uploadSpeed": "Loading",
			"uploadSpeedMetric": "mb/s",
			"downloadSpeed": "Loading",
			"downloadSpeedMetric": "mb/s",
			"maxBandwidthPercent": "5",
			"maxMonthlyBandwidth": "100",
			"maxMonthlyBandwidthMetric": "mb",
      "monthlyBandwidthUsage": "23",
			"on": True
		},
    "wanIp"  : wan_ip,
    "lanIp"  : lan_ip
	}
}

print "Content-Type:application/json\r\n"
print json.JSONEncoder().encode(result)
