#!/usr/bin/env python2.7
import json
import os
import sys

import auth
import common
import uci
from audit import Audit
from datetime import datetime

def jsonrpc_login():
    """Accept a JSONRPC-style login, with parameters like so:

    {"jsonrpc":"2.0","method":"login","params":["username","password"],"id":1}
    """
    data = json.loads(sys.stdin.read())
    try:
        params = data["params"]
        username = params[0]
        password = params[1]
    except KeyError, e:
        common.render_error(e.__str__())
    a = auth.Auth()
    tokens = a.authenticate(password)
    if tokens:
        audit = Audit(uci)
        remote_address = os.environ.get('REMOTE_ADDR')
        audit.record_login(remote_address, datetime.utcnow())
        print "Content-Type: application/json"
        print a.login_headers(tokens)
        print
        print "{}"
    else:
        common.render_error("Bad password.")

jsonrpc_login()
