#!/usr/bin/env python2.7
import json
import os
import sys

import auth
import common

def jsonrpc_login():
    """Accept a JSONRPC-style login, with parameters like so:

    {"jsonrpc":"2.0","method":"login","params":["username","password"],"id":1}
    """
    data = json.loads(sys.stdin.read())
    try:
        params = data["params"]
        username = params[0]
        password = params[1]
    except KeyError, e:
        common.render_error(e.__str__())
    a = auth.Auth()
    remote_address = os.environ.get('REMOTE_ADDR')
    tokens = a.authenticate(password, remote_address)
    if tokens:
        print "Content-Type: application/json"
        print a.login_headers(tokens)
        print
        print "{}"
    else:
        common.render_error("Bad password.")

jsonrpc_login()
