#!/usr/bin/python

import json
import os
import common
import sys
import uci
from get_bytecounts import get_device_and_byte_counts

[x, upload_usage, download_usage] = get_device_and_byte_counts("open-wifi")

current_usage = float(upload_usage) + float(download_usage)

uci.set("openwireless.use_at_last_ui_reset", str(current_usage))
uci.set("openwireless.use_before_last_reset", "0")
uci.set("openwireless.use_since_last_reset", "0")
uci.commit("openwireless")

response = {}

common.render_success(response)
