#!/usr/bin/env python2.7

import json
import os
import common
import sys
import uci

max_use = float(uci.get("openwireless.maxmonthlybandwidth"))*1000000
uci.set("openwireless.use_since_last_ui_reset", "0")
uci.commit("openwireless")

current_state = uci.get("wireless.@wifi-iface[1].disabled")
new_state = "0" if max_use > 0 else "1"
if current_state != new_state:
    uci.set("wireless.@wifi-iface[1].disabled", new_state)
    uci.commit("wireless")
    common.reset_wifi()

response = {}

common.render_success(response)