#!/usr/bin/env python2.7
"""
Setup state.

During initial setup, the router can be in one of these states:
    set-password
    setup-private-net
    setup-public-net
    complete

When requested via GET, this endpoint will return a JSON object containing
the current state:

    { 'state': 'set-password'}
"""

import os

import uci
import common

VALID_SETUP_STATES = [
         'set-password',
         'setup-private-net',
         'setup-public-net',
         'complete'
]

def get_setup_state():
    state = uci.get('openwireless.setup_state')
    if not state:
      state = 'set-password'

    if state in VALID_SETUP_STATES:
        common.render_success({'state': state})
    else:
        common.render_error('Invalid setup state')

get_setup_state()
