#!/usr/bin/python
"""
   Setup state.

   During initial setup, the router can be in one of these states:
     set-password
     setup-private-net
     setup-public-net
     complete

   When requested via GET, this endpoint will return a JSON object containing
   the current state:

     { "state": "set-password"}
"""

import os
import common

SETUP_STATE_PATH = os.path.join(common.get_etc(), 'openwireless-setup-state')
VALID_SETUP_STATES = [
     "set-password",
     "setup-private-net",
     "setup-public-net",
     "complete"
]

def get_setup_state():
  if os.path.isfile(SETUP_STATE_PATH):
    with open(SETUP_STATE_PATH, 'r') as f:
      state = f.read().strip()
    if state in VALID_SETUP_STATES:
      common.render_success({"state": state})
    else:
      common.render_error('Invalid setup state')
  else:
    common.render_success({"state": "set-password"})

get_setup_state()
