#!/usr/bin/env python2.7
import json
import os
import sys

import check_interface_connection
import common
import uci

response = {}

interface_dictionary = {"Openwireless.org": 1, "Private WiFi": 2}

def toggle_wireless_status(interface_index):
    config_variable = "wireless.@wifi-iface[%d].disabled" % interface_index
    if not check_interface_connection.enabled(interface_index):
        uci.set(config_variable, "0")
        uci.commit("wireless")
        common.reset_wifi()
        return "on"
    else:
        uci.set(config_variable, "1")
        uci.commit("wireless")
        common.reset_wifi()
        return "off"

if os.environ.get('REQUEST_METHOD') == 'POST':
    json_body = json.loads(sys.stdin.read())
    interface_index = interface_dictionary[json_body["name"]]
    response["name"] = json_body["name"]
    response["new_state"] = toggle_wireless_status(interface_index)
else:
    common.render_error('Received GET request. Requires POST.')

common.render_success(response)
