#!/usr/bin/python

import os, json, sys, uci, common

environ = os.environ
params = {}
response = {}

interface_dictionary = {"Openwireless.org": "1", "Private WiFi": "3"}

def wireless_is_disabled(interface_name):
    is_disabled = uci.get("wireless.@wifi-iface[" + interface_name + "].disabled") == "1"
    return is_disabled


def toggle_wireless_status(interface_name):
    if wireless_is_disabled(interface_name):
        uci.set("wireless.@wifi-iface[" + interface_name + "].disabled=0")
        return "On"
    else:
        uci.set("wireless.@wifi-iface[" + interface_name + "].disabled=1")
        return "Off"
    uci.commit("wireless")

def set_error(param):
    response['error'] = 'Invalid ' + param

if environ.get('REQUEST_METHOD', 'GET').lower() == 'post':
    json_body = json.loads(sys.stdin.read())

    for k in json_body.keys():
        params[k] = json_body[k]

    response["name"] = params["name"]
    response["new_state"] = toggle_wireless_status(interface_dictionary[params["name"]])

else:
    set_error('GET request')

print "Content-Type:application/json\r\n"
print json.JSONEncoder().encode(response)
