#!/usr/bin/python

import os, json, sys, uci, common
from check_interface_connection import wireless_is_disabled

environ = os.environ
params = {}
response = {}

interface_dictionary = {"Openwireless.org": "1", "Private WiFi": "2"}

def toggle_wireless_status(interface_name):
    config_variable = "wireless.@wifi-iface[" + interface_name + "].disabled"
    if wireless_is_disabled(interface_name):
        uci.set(config_variable + "=0")
        uci.commit("wireless")
        common.reset_wifi()
        return "On"
    else:
        uci.set(config_variable + "=1")
        uci.commit("wireless")
        common.reset_wifi()
        return "Off"

if environ.get('REQUEST_METHOD', 'GET').lower() == 'post':
    json_body = json.loads(sys.stdin.read())

    for k in json_body.keys():
        params[k] = json_body[k]

    response["name"] = params["name"]
    response["new_state"] = toggle_wireless_status(interface_dictionary[params["name"]])
else:
    common.render_error('Received GET request. Requires POST.')

common.render_success(response)
