#!/usr/bin/env python2.7
import cgi
import common

nullfile = open("/dev/null","w")
ret = "error-calling-update"

try:
    if subprocess.call(["/usr/bin/sudo", "/lib/update/update.py"], stdout=nullfile) == 0:
      ret = "update-success" # Should never reach this line of code
    else:
      ret = "update-failure"
except OSError:
    # catch call-errors and return error message
    pass
finally:
    nullfile.close()

result = {
    "result": {
        "status": ret
    }
}

common.render_success(result)

