#!/usr/bin/env python2.7
import cgi
import json
import subprocess

import auth
import common

if subprocess.call(["python", "/lib/update/update.py"]) == 0:
  ret = "update-success" # Should never reach this line of code
else:
  ret = "update-failure"

result = {
  "result": {
    "status": ret
  }
}

common.render_success(result)

