#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=71
USE_PROCD=1
EXTRA_COMMANDS="status"
EXTRA_HELP="        status Print ahcpd's status to the log file."
PROG=/usr/sbin/ahcpd
CONFIGFILE=/var/etc/ahcpd.conf
MODE=client

xappend() {
	echo $* >> $CONFIGFILE
}

append_file_bool() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _loctmp
	config_get_bool _loctmp "$section" "$option" 0
	[ "$_loctmp" -gt 0 ] && xappend $switch $value
}

append_bool() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _loctmp
	config_get_bool _loctmp "$section" "$option" 0
	[ "$_loctmp" -gt 0 ] && append args "$switch $value"
}

append_file_parm() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local _loctmp
	config_get _loctmp "$section" "$option"
	[ -z "$_loctmp" ] && return 0
	xappend $switch $_loctmp
}

append_parm() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local _loctmp
	config_get _loctmp "$section" "$option"
	[ -z "$_loctmp" ] && return 0
	append args "$switch $_loctmp"
}

append_stmt() {
	local name="$1"
	local switch="$2"
	xappend $switch $name
}

append_opt_stmt() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local _loctmp
	config_get _loctmp "$section" "$option"
	[ -z "$_loctmp" ] && return 0
	xappend $switch $_loctmp
}

ahcp_addif() {
	local ifname=$(uci_get_state network "$1" ifname "$1")
	append interfaces "$ifname"
}

ahcp_validate_server() {
	append_opt_stmt "$cfg" 'mode' 'mode'
	append_opt_stmt "$cfg" 'lease_dir' 'lease-dir'
	config_list_foreach "$cfg" 'prefix' append_stmt 'prefix'
	config_list_foreach "$cfg" 'name_server' append_stmt 'name-server'
	config_list_foreach "$cfg" 'ntp_server' append_stmt 'ntp-server'

	append_parm "$cfg" 'id_file' '-i'
	append_parm "$cfg" 'log_file' '-L'

}

ahcp_server() {
	local cfg="$1"
	
	if [ "$MODE" = "server" ]
	then
	append_opt_stmt "$cfg" 'mode' 'mode'
	append_opt_stmt "$cfg" 'lease_dir' 'lease-dir'
	
	config_list_foreach "$cfg" 'prefix' append_stmt 'prefix'
	config_list_foreach "$cfg" 'name_server' append_stmt 'name-server'
	config_list_foreach "$cfg" 'ntp_server' append_stmt 'ntp-server'

	append_parm "$cfg" 'id_file' '-i'
	fi
	append_parm "$cfg" 'log_file' '-L'
}

ahcp_config() {
	local cfg="$1"
	local interface
	local _loctmp

	config_list_foreach "$cfg" 'interface' ahcp_addif

	# Add interfaces with "option proto ahcp" in /etc/config/network
	config_get _loctmp "$cfg" "mode"
	if [ -z "$_loctmp" -o "$_loctmp" = "client" ]; then
		for interface in $(uci -P /var/state show network|grep proto=ahcp|cut -d. -f2); do
			ahcp_addif $interface
		done
	MODE=client
	fi
	if [ "$_loctmp" = "server" ]; then
#		for interface in $(uci -P /var/state show network|grep proto=ahcp|cut -d. -f2); do
#			ahcp_addif $interface
#		done
	MODE=server
	fi
	if [ "$_loctmp" = "forwarder" ]; then
#		for interface in $(uci -P /var/state show network|grep proto=ahcp|cut -d. -f2); do
#			ahcp_addif $interface
#		done
	MODE=forwarder
	fi

	append_bool "$cfg" 'ipv4_only' '-4'
	append_bool "$cfg" 'ipv6_only' '-6'
	append_bool "$cfg" 'no_dns' '-N'

	append_parm "$cfg" 'multicast_address' '-m'
	append_parm "$cfg" 'port' '-p'
	append_parm "$cfg" 'lease_time' '-t'
	append_parm "$cfg" 'debug' '-d'
	append_parm "$cfg" 'conf_file' '-c'
	append_parm "$cfg" 'script' '-s'
}

start_service() {
	mkdir -p /var/lib/leases
	mkdir -m 0755 -p `dirname $CONFIGFILE`
	> $CONFIGFILE
	chmod og-rwx $CONFIGFILE
	config_load ahcpd
	unset args
	unset interfaces
	config_foreach ahcp_config ahcpd
	config_foreach ahcp_server ahcpd
	echo $args
	[ -z "$interfaces" ] && return 0
        procd_open_instance
        # ahcpd is really finicky about conf files
        if [ "$MODE" != "client" ]
        then
        procd_set_param command $PROG $args -c $CONFIGFILE $interfaces
	procd_set_param file $CONFIGFILE
        else
        procd_set_param command $PROG $args $interfaces
        fi
	procd_set_param respawn
        procd_close_instance
}

status() {
	SERVICE_SIG="USR1" service_signal /usr/sbin/ahcpd
}
