#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org
START=61
USE_PROCD=1

PROG=/usr/sbin/avahi-daemon
CONFIGFILE=/etc/avahi/avahi-daemon.conf

start_service() {
        procd_open_instance
        procd_set_param command $PROG -s
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
        procd_close_instance
}

reload() {
	$PROG -r
}

