#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
PROG=/usr/sbin/lighttpd
CONFIGFILE=/etc/lighttpd/lighttpd.conf
LOGDIR=/var/log/lighttpd
USE_PROCD=1

start_service() {
	mkdir -m 0755 -p $LOGDIR

        procd_open_instance
        procd_set_param command $PROG -D -f $CONFIGFILE
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
        procd_close_instance

}

